/**
 * Real grounding data for Bangalore Rural district (Channapatna's district),
 * extracted from Census 2011 District Census Handbook - Bangalore Rural
 * (part of the combined dataset PDF). All figures below are directly from
 * the source document, not estimated or rounded beyond what the source states.
 *
 * Field names/types match lib/ai/mock-grounding.ts's GroundingRow exactly:
 * stat_value is a string (source data here was numeric — converted to
 * string, not rounded), and source_url/tag were added since GroundingRow
 * requires both (source_url: null — no URL for this PDF; tag: "verified"
 * since these are real, sourced stats).
 */

import type { GroundingRow } from "./mock-grounding";

export const REAL_GROUNDING_BANGALORE_RURAL: GroundingRow[] = [
  {
    id: "gd_real_001",
    location: "Bangalore Rural",
    sector: "demographics",
    stat_name: "sex_ratio",
    stat_value: "945",
    unit: "females per 1000 males",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
  {
    id: "gd_real_002",
    location: "Bangalore Rural",
    sector: "demographics",
    stat_name: "overall_literacy_rate",
    stat_value: "75.16",
    unit: "%",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
  {
    id: "gd_real_003",
    location: "Bangalore Rural",
    sector: "demographics",
    stat_name: "sc_literacy_rate",
    stat_value: "67.29",
    unit: "%",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
  {
    id: "gd_real_004",
    location: "Bangalore Rural",
    sector: "demographics",
    stat_name: "sc_population_share",
    stat_value: "21.57",
    unit: "% of total population",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
  {
    id: "gd_real_005",
    location: "Bangalore Rural",
    sector: "workforce",
    stat_name: "total_worker_participation_rate",
    stat_value: "46.41",
    unit: "% of total population",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
  {
    id: "gd_real_006",
    location: "Bangalore Rural",
    sector: "workforce",
    stat_name: "male_worker_participation_rate",
    stat_value: "61.96",
    unit: "%",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
  {
    id: "gd_real_007",
    location: "Bangalore Rural",
    sector: "workforce",
    stat_name: "female_worker_participation_rate",
    stat_value: "29.97",
    unit: "%",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
  {
    id: "gd_real_008",
    location: "Bangalore Rural",
    sector: "workforce",
    stat_name: "main_workers_share",
    stat_value: "40.51",
    unit: "% of workers",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
  {
    id: "gd_real_009",
    location: "Bangalore Rural",
    sector: "workforce",
    stat_name: "marginal_workers_share",
    stat_value: "8.04",
    unit: "% of workers",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
  {
    id: "gd_real_010",
    location: "Bangalore Rural",
    sector: "agriculture",
    stat_name: "cultivators_and_agri_labourers_share",
    stat_value: "46.07",
    unit: "% of total workers",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
  {
    id: "gd_real_011",
    location: "Bangalore Rural",
    sector: "infrastructure",
    stat_name: "total_road_length",
    stat_value: "6169",
    unit: "km (as of 2009-10)",
    source: "Bangalore Rural District at a Glance 2009-10, District Statistical Office",
    source_url: null,
    source_year: 2010,
    tag: "verified",
  },
  {
    id: "gd_real_012",
    location: "Bangalore Rural",
    sector: "infrastructure",
    stat_name: "villages_with_power_supply",
    stat_value: "98.33",
    unit: "% of villages",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
  {
    id: "gd_real_013",
    location: "Bangalore Rural",
    sector: "infrastructure",
    stat_name: "villages_with_pucca_road_access",
    stat_value: "84.95",
    unit: "% of villages",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
  {
    id: "gd_real_014",
    location: "Bangalore Rural",
    sector: "finance_access",
    stat_name: "villages_with_banking_facility",
    stat_value: "7.63",
    unit: "% of villages",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
  {
    id: "gd_real_015",
    location: "Bangalore Rural",
    sector: "finance_access",
    stat_name: "villages_with_agricultural_credit_society",
    stat_value: "1.57",
    unit: "% of villages",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
  {
    id: "gd_real_016",
    location: "Bangalore Rural",
    sector: "communication",
    stat_name: "post_offices_count",
    stat_value: "108",
    unit: "count (district total)",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
  {
    id: "gd_real_017",
    location: "Bangalore Rural",
    sector: "communication",
    stat_name: "telephone_connections_count",
    stat_value: "53498",
    unit: "count (district total)",
    source: "Census 2011 District Census Handbook - Bangalore Rural",
    source_url: null,
    source_year: 2011,
    tag: "verified",
  },
];

// From the earlier clean summary PDF (Bengaluru Rural & Region Profile), already validated:
export const REAL_GROUNDING_BANGALORE_RURAL_SECTORAL: GroundingRow[] = [
  {
    id: "gd_real_018",
    location: "Bangalore Rural",
    sector: "handicrafts",
    stat_name: "channapatna_artisan_count",
    stat_value: "3000",
    unit: "artisans (approx, 1000+ units)",
    source: "Bengaluru Rural & Region Profile - Sectoral Statistics",
    source_url: null,
    source_year: 2024,
    tag: "verified",
  },
  {
    id: "gd_real_019",
    location: "Bangalore Rural",
    sector: "sericulture",
    stat_name: "mulberry_cultivation_area",
    stat_value: "20800",
    unit: "hectares (approx)",
    source: "Bengaluru Rural & Region Profile - Sectoral Statistics",
    source_url: null,
    source_year: 2024,
    tag: "verified",
  },
  {
    id: "gd_real_020",
    location: "Bangalore Rural",
    sector: "sericulture",
    stat_name: "registered_sericulturist_families",
    stat_value: "26000",
    unit: "families (approx, 26,000+)",
    source: "Bengaluru Rural & Region Profile - Sectoral Statistics",
    source_url: null,
    source_year: 2024,
    tag: "verified",
  },
];
